### PR TITLE
Fix edit command year group issue

### LINKED ISSUE #174: Wrong prefix in description for edit command
image

Description states yeargroup prefix as i/ instead of yg/

### PR DESCRIPTION
**Pull request by cweijin**
Fixes #174 #175

### CODE REVIEW

File: src/main/java/seedu/academyassist/logic/parser/EditCommandParser.java [hunk 1]
```diff
@@ -62,6 +63,10 @@ public EditCommand parse(String args) throws ParseException {
         if (argMultimap.getValue(PREFIX_IC).isPresent()) {
             editPersonDescriptor.setIc(ParserUtil.parseIc(argMultimap.getValue(PREFIX_IC).get()));
         }
+        if (argMultimap.getValue(PREFIX_YEARGROUP).isPresent()) {
+            editPersonDescriptor.setYearGroup((ParserUtil.parseYearGroup(argMultimap.getValue(
+                    PREFIX_YEARGROUP).get())));
```
Comment (JoanneHing) [inline src/main/java/seedu/academyassist/logic/parser/EditCommandParser.java:68]: Good job to notice what is missed out!

**Review by JoanneHing — APPROVED** [review]
LGTM! Thanks for fixing the bug!
