### PR TITLE
Update add subject to fix person card issue

### LINKED ISSUE #160: Student contacts reordered when I added a new subject
When I add a new subject to a student, the student goes to the bottom of the list. Would it be possible to make the student contact stay at its original position and just update the subjects? If not, perhaps we could sort the students automatically by studentID after we add the subject so that the contacts are listed in their original order?

### LINKED ISSUE #190: Suggestion for using setPerson in add class
Add command places target person to the end of `PersonList`, resulting in sudden movement of `PersonCard` in the UI. This prevents users from seeing changes they made immediately and may cause confusion.

Suggestion: Use the `setPerson` method that comes with AB3 to modify the target person 'in-place'.

### PR DESCRIPTION
**Pull request by cweijin**
Fixes #160 
Fixes #190

### CODE REVIEW

File: src/main/java/seedu/academyassist/model/AcademyAssist.java [hunk 1]
```diff
@@ -173,11 +173,11 @@ public boolean personDuplicateClass(Set<Subject> subjects, Person student) {
...
      */
     public void addSubjectsToPerson(Set<Subject> subjects, Person person) {
-        persons.remove(person);
+        Person updatedPerson = person;
         for (Subject s: subjects) {
-            person = person.addSubject(s);
+            updatedPerson = updatedPerson.addSubject(s);
         }
-        persons.add(person);
+        persons.setPerson(person, updatedPerson);
```
Comment (JoanneHing) [inline src/main/java/seedu/academyassist/model/AcademyAssist.java:180]: Good that you use setPerson for updated Person to avoid deleting and adding again!

File: src/test/java/seedu/academyassist/model/AcademyAssistTest.java [hunk 2]
```diff
@@ -75,6 +78,28 @@ public void hasPerson_personWithSameIdentityFieldsInAcademyAssist_returnsTrue()
...
+        academyAssist.addPerson(ALICE);
+        //Alice already taking English
+        Person updatedAlice = new PersonBuilder(ALICE).withSubjects("English", "Math", "Chinese", "Science").build();
+        Set<Subject> subjectsToAdd = new HashSet<>(List.of(new Subject("Math"), new Subject("Chinese"),
+                new Subject("Science")));
+        academyAssist.addSubjectsToPerson(subjectsToAdd, ALICE);
+        assertTrue(academyAssist.getPersonList().contains(updatedAlice));
+    }
+
+
```
Comment (JoanneHing) [inline src/test/java/seedu/academyassist/model/AcademyAssistTest.java:102]: Thank you for updating the test cases together also!

**Review by JoanneHing — APPROVED** [review]
LGTM!
