### PR TITLE
Remove tags and fix test cases

### LINKED ISSUE #76: Update test cases for add feature

### LINKED ISSUE #113: Remove tags from a person

### PR DESCRIPTION
**Pull request by annabellekk**
Fixes #113 
Fixes #76

### CODE REVIEW

File: src/test/java/seedu/academyassist/logic/commands/CommandTestUtil.java [hunk 1]
```diff
@@ -43,9 +43,8 @@ public class CommandTestUtil {
     public static final String VALID_IC_ALICE = "F2234567X";
     public static final String VALID_SUBJECT_AMY = "English";
     public static final String VALID_SUBJECT_BOB = "Science";
-    public static final String VALID_TAG_HUSBAND = "husband";
-    public static final String VALID_TAG_FRIEND = "friend";
```
Comment (cweijin) [inline src/test/java/seedu/academyassist/logic/commands/CommandTestUtil.java:47]: Thanks for cleaning up the constants!

File: src/test/java/seedu/academyassist/logic/parser/EditCommandParserTest.java [hunk 2]
```diff
@@ -84,19 +77,18 @@ public void parse_invalidValue_failure() {
...
-        assertParseFailure(parser, "F1264567X" + TAG_EMPTY + TAG_DESC_FRIEND + TAG_DESC_HUSBAND,
-                Tag.MESSAGE_CONSTRAINTS);
+        //        // while parsing {@code PREFIX_TAG} alone will reset the tags of the {@code Person} being edited,
+        //        // parsing it together with a valid tag results in error
+        //        assertParseFailure(parser, "F1264567X" + TAG_DESC_FRIEND + TAG_DESC_HUSBAND + TAG_EMPTY,
+        //                Tag.MESSAGE_CONSTRAINTS);
+        //        assertParseFailure(parser, "F1264567X" + TAG_DESC_FRIEND + TAG_EMPTY + TAG_DESC_HUSBAND,
+        //                Tag.MESSAGE_CONSTRAINTS);
+        //        assertParseFailure(parser, "F1264567X" + TAG_EMPTY + TAG_DESC_FRIEND + TAG_DESC_HUSBAND,
+        //                Tag.MESSAGE_CONSTRAINTS);
```
Comment (cweijin) [inline src/test/java/seedu/academyassist/logic/parser/EditCommandParserTest.java:91]: Is there any reason we're keeping these lines?

File: src/test/java/seedu/academyassist/logic/parser/ParserUtilTest.java [hunk 3]
```diff
@@ -149,48 +147,51 @@ public void parseEmail_validValueWithWhitespace_returnsTrimmedEmail() throws Exc
...
+        assertThrows(ParseException.class, () -> ParserUtil.parseSubjects(Arrays.asList(VALID_SUBJECT_1,
+                INVALID_SUBJECT)));
     }
 
+    // todo check the below
     @Test
-    public void parseTags_emptyCollection_returnsEmptySet() throws Exception {
-        assertTrue(ParserUtil.parseTags(Collections.emptyList()).isEmpty());
+    public void parseSubjects_emptyCollection_throwsParseException() throws Exception {
+        assertThrows(ParseException.class, () -> ParserUtil.parseSubjects(Collections.emptyList()).isEmpty());
```
Comment (cweijin) [inline src/test/java/seedu/academyassist/logic/parser/ParserUtilTest.java:186]: Perhaps remove `isEmpty()`? It seems unnecessary since it won't execute if `parseSubjects` throws `ParseException`.

File: src/test/java/seedu/academyassist/model/person/SubjectTest.java [hunk 4]
```diff
@@ -0,0 +1,24 @@
...
+        String invalidSubjectName = "";
+        assertThrows(IllegalArgumentException.class, () -> new Subject(invalidSubjectName));
+    }
+
+    @Test
+    public void isValidSubjectName() {
+        // null tag name
+        assertThrows(NullPointerException.class, () -> Subject.isValidSubject(null));
+    }
+}
```
Comment (cweijin) [inline src/test/java/seedu/academyassist/model/person/SubjectTest.java:24]: Thanks for crafting the test cases for Subject!

**Review by cweijin — APPROVED** [review]
LGTM!

File: src/test/java/seedu/academyassist/storage/JsonAdaptedPersonTest.java [hunk 5]
```diff
@@ -101,27 +101,63 @@ public void toModelType_nullEmail_throwsIllegalValueException() {
...
+        String expectedMessage = YearGroup.MESSAGE_CONSTRAINTS;
+        assertThrows(IllegalValueException.class, expectedMessage, person::toModelType);
+    }
+    @Test
+    public void toModelType_nullYearGroup_throwsIllegalValueException() {
+        JsonAdaptedPerson person = new JsonAdaptedPerson(VALID_NAME, VALID_PHONE, VALID_EMAIL, VALID_ADDRESS, VALID_IC,
+                null, VALID_SUBJECTS);
+        String expectedMessage = String.format(MISSING_FIELD_MESSAGE_FORMAT, YearGroup.class.getSimpleName());
+        assertThrows(IllegalValueException.class, expectedMessage, person::toModelType);
+    }
```
Comment (JoanneHing) [inline src/test/java/seedu/academyassist/storage/JsonAdaptedPersonTest.java:162]: A nitpick, maybe can add new lines before each test for better readability?

File: src/test/java/seedu/academyassist/testutil/EditPersonDescriptorBuilder.java [hunk 6]
```diff
@@ -75,12 +74,13 @@ public EditPersonDescriptorBuilder withAddress(String address) {
...
+     * Parses the {@code subjects} into a {@code Set<Subject>} and set it to the {@code EditPersonDescriptor}
      * that we are building.
      */
-    public EditPersonDescriptorBuilder withTags(String... tags) {
-        Set<Tag> tagSet = Stream.of(tags).map(Tag::new).collect(Collectors.toSet());
-        descriptor.setTags(tagSet);
+    public EditPersonDescriptorBuilder withSubjects(String... subjects) {
+        Set<Subject> subjectSet = Stream.of(subjects).map(subject -> new Subject(subject.toUpperCase()))
+                .collect(Collectors.toSet());
+        descriptor.setSubjects(subjectSet);
```
Comment (JoanneHing) [inline src/test/java/seedu/academyassist/testutil/EditPersonDescriptorBuilder.java:83]: Good job to continue implement this with stream!

File: src/main/java/seedu/academyassist/model/person/Person.java [hunk 7]
```diff
@@ -66,20 +63,16 @@ public Ic getIc() {
...
      */
-    public Set<Tag> getTags() {
-        return Collections.unmodifiableSet(tags);
+    public Set<Subject> getSubjects() {
+        return Collections.unmodifiableSet(subjects);
     }
 
     /**
-     * Returns true if both persons have the same name.
+     * Returns true if both persons have the same IC.
```
Comment (JoanneHing) [inline src/main/java/seedu/academyassist/model/person/Person.java:75]: Good that you notice that the header comment is incorrect here!

File: src/main/java/seedu/academyassist/storage/JsonAdaptedPerson.java [hunk 8]
```diff
@@ -127,12 +113,16 @@ public Person toModelType() throws IllegalValueException {
...
+            throw new IllegalValueException(String.format(MISSING_FIELD_MESSAGE_FORMAT,
+                    YearGroup.class.getSimpleName()));
+        }
         if (!YearGroup.isValidYearGroup(yearGroup)) {
             throw new IllegalValueException(YearGroup.MESSAGE_CONSTRAINTS);
         }
         final YearGroup modelYearGroup = new YearGroup(yearGroup);
 
-        if (subjects == null) {
+        if (subjects == null || subjects.isEmpty()) {
```
Comment (JoanneHing) [inline src/main/java/seedu/academyassist/storage/JsonAdaptedPerson.java:125]: Good for the validation checking here!

**Review by JoanneHing — COMMENTED** [review]
LGTM! Overall good coding practice and styles!

File: src/main/java/seedu/academyassist/logic/parser/ParserUtil.java [hunk 9]
```diff
@@ -104,6 +103,9 @@ public static Subject parseSubject(String subject) throws ParseException {
      */
     public static Set<Subject> parseSubjects(Collection<String> subjects) throws ParseException {
         requireNonNull(subjects);
+        if (subjects.isEmpty()) {
+            throw new ParseException("Subjects cannot be empty");
```
Comment (ethanwangkangen) [inline src/main/java/seedu/academyassist/logic/parser/ParserUtil.java:107]: Nice that you checked for empty subject case!

**Review by ethanwangkangen — APPROVED** [review]
LGTM overall! Will merge this
