### PR TITLE
Fix name validation to only accept alphabets

### LINKED ISSUE #177: Can add person with numbers in name but cannot search for it
image
image

Should either make it such that no numbers allowed in name, or can search for it

### PR DESCRIPTION
**Pull request by annabellekk**
Fixes #177 #178

### CODE REVIEW

File: src/main/java/seedu/academyassist/model/person/Name.java [hunk 1]
```diff
@@ -11,13 +11,14 @@
 public class Name {
 
     public static final String MESSAGE_CONSTRAINTS =
-            "Names should only contain alphanumeric characters and spaces, and it should not be blank";
+            "Names should only contain alphabets and spaces. Names should not start with a space and should not be "
```
Comment (JoanneHing) [inline src/main/java/seedu/academyassist/model/person/Name.java:14]: Good to check it is not stated with a space!

**Review by JoanneHing — APPROVED** [review]
LGTM!
